name: CI
on:
  push:
    branches:
      - bats
    workflow_dispatch:

jobs:
  bats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bash: ["bash:3.2", "bash:4.4", "bash:5.0", "bash:5.1"]
    container:
      image: ${{ matrix.bash }}

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Run main tests
        run: bats test/main.bats

      - name: Run output tests
        run: bats test/output.bats

      - name: Run validator tests
        run: bats test/validators.bats

      - name: Run prompts tests
        run: bats test/prompts.bats

      - name: Run install_prep tests
        run: bats test/install_prep.bats

      - name: Run preinstall tests
        run: bats test/preinstall.bats
      
      - name: Run install tests
        run: bats test/install.bats

      - name: Run cleanup tests
        run: bats test/cleanup.bats
