name: CI
on:
  push:
    branches:
      - bats
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.5.0
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: bats/test.main.bats
