name: CI
on:
  push:
    branches: [ "bats" ]
  pull_request:
    branches: [ "bats" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - uses: actions/checkout@v3

      - name: Test
        run: bats test/install_prep.bats

