name: CI
on:
  push:
    branches:
      - bats
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Run main tests
        run: bats test/main.bats

      - name: Run output tests
        run: bats test/output.bats

      - name: Run validator tests
        run: bats test/validators.bats

      - name: Run prompts tests
        run: bats test/prompts.bats

      - name: Run install_prep tests
        run: bats test/install_prep.bats

      - name: Run cleanup tests
        run: bats test/cleanup.bats
